/*
 * Copyright (C) 2022 Jose
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package cu.edu.cujae.ed.snetwork.ui;

import cu.edu.cujae.ed.snetwork.logic.ApplicationController;
import cu.edu.cujae.ed.snetwork.logic.Person;
import cu.edu.cujae.ed.snetwork.serializers.PersonExporter;
import cu.edu.cujae.ed.snetwork.utils.FileManager;
import cu.edu.cujae.ed.snetwork.utils.SaveTXT;
import cu.edu.cujae.ed.snetwork.utils.TreeUtils;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import javax.imageio.ImageIO;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import org.flexdock.docking.DockingConstants;
import org.flexdock.view.View;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Jose
 */
public class MainWindow extends javax.swing.JFrame
{

    private Logger logger;
    private SidePanel sidePanel;
    private JPanel graphView;
    private View firstDocked = null;
    private View first = null;
    private final FileManager fileManager;

    public FileManager getFileManager()
    {
        return fileManager;
    }
    private boolean isOpened;
    private CloseableView cv;
    private CloseableView sa;
    private boolean isOSE;

    public boolean isIsOSE()
    {
        return isOSE;
    }

    public void setIsOSE(boolean isOSE)
    {
        this.isOSE = isOSE;
    }

    public CloseableView getSa()
    {
        return sa;
    }

    public void setSa(CloseableView sa)
    {
        this.sa = sa;
    }

    public CloseableView getCv()
    {
        return cv;
    }

    public void setCv(CloseableView cv)
    {
        this.cv = cv;
    }

    public boolean isIsOpened()
    {
        return isOpened;
    }

    public void setIsOpened(boolean isOpened)
    {
        this.isOpened = isOpened;
    }

    /**
     * Creates new form MainWindow
     */
    public MainWindow(FileManager fileManager) throws IOException
    {
        initComponents();
        this.fileManager = fileManager;
        this.isOpened = false;
        this.sidePanel = new SidePanel();
        this.graphView = new JPanel();

        this.isOSE = false;
        dock(graphView, DockingConstants.CENTER_REGION, 1.0f);
        first = dock(sidePanel, DockingConstants.WEST_REGION, 0.40f);
        
        logger = LoggerFactory.getLogger(MainWindow.class);
        
        sidePanel.addSelectionListener((var person) ->        {
            if (!isOpened)
            {
            Autenticacion a = new Autenticacion(this, false, person);
            a.setVisible(true);
            
                logger.info("{}, pwd {} y pais {}", person.getName(), person.getPassword(), person.getCountry());
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Cierre el perfil actual para abrir uno nuevo", "",
                                              JOptionPane.INFORMATION_MESSAGE);
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        dockingPort = new org.flexdock.view.Viewport();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SocialNetWork");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        dockingPort.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(dockingPort, java.awt.BorderLayout.CENTER);

        jMenu2.setText("App");

        jMenuItem6.setText("Insertar Usuario ");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);
        jMenu2.add(jSeparator2);

        jMenuItem2.setText("Acerca de ...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);
        jMenu2.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Reportes");
        jMenu1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Islas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem4.setText("Comunidades");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setText("Líderes de investigación");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem2ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem2ActionPerformed
        Creditos cr = new Creditos(this, true);
        cr.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem3ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem3ActionPerformed
        try {
        LinkedList<Person> list = ApplicationController.getInstance().getResearchLeaders();
            LideresInvestigacion li = new LideresInvestigacion(this, false, list, fileManager);
        li.setVisible(true);
        } catch (IllegalStateException ex) {
            JOptionPane.showMessageDialog(null, "No existen personas en la red social", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenu1ActionPerformed
    {//GEN-HEADEREND:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem5ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem5ActionPerformed
        try {
        LinkedList<Person> p = ApplicationController.getInstance().isolatedPersons();
            IsolatedVertices iv = new IsolatedVertices(this, false, p, fileManager);
        iv.setVisible(true);
            try
            {
                SaveTXT.saveIsolatedVertices(p, fileManager);
            }
            catch (IOException ex)
            {
                java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        catch (IllegalStateException ex)
        {
            JOptionPane.showMessageDialog(null, "No existen personas en la red social", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem4ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem4ActionPerformed
        ArrayList<ArrayList<Person>> communities = ApplicationController.getInstance().getCommunities();
        Communities c = new Communities(this, false, communities,fileManager);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem6ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem6ActionPerformed
        InsertarPersona ip = new InsertarPersona(this);
        ip.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        try
        {
            ApplicationController.getInstance().saveGraph();
            ArrayList<Person> people = ApplicationController.getInstance().getPersons();
                        for (Person p : people)
                        {
                            File ppicDir = new File(fileManager.getPicsDirectory(), p.getID());
                            ppicDir.mkdir();
                        }

            PersonExporter exp = new PersonExporter(people, fileManager);
            exp.serialize();
            ApplicationController.getInstance().saveNotifications();
        }
        catch (IOException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowClosing
    
    public final CloseableView dockSP(JComponent dockable, String region, float size){
        CloseableView cv = new CloseableView(dockable.getName());
        cv.setContentPane(dockable);

        if (dockingPort.getDockables().isEmpty())
        {
            dockingPort.dock(cv);
            first = cv;
        }
        else
        {
            first.dock(cv, region, size);
        }
        return cv;
    }
    
    public final CloseableView dock(JComponent dockable, String region, float size)
    {
        CloseableView cv = new CloseableView(dockable.getName());
        cv.setContentPane(dockable);
        if (dockingPort.getDockables().isEmpty())
        {
            dockingPort.dock(cv);
            firstDocked = cv;
        }
        else 
        {
            firstDocked.dock(cv, region, size);
        }
        return cv;
    }
    
    public void closeCv()
    {
        dockingPort.undock(cv);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.flexdock.view.Viewport dockingPort;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
 public SidePanel getSidePanel()
    {
        return sidePanel;
    }
 
 public void revalidatePhoto(){
      for (SideBarButton button : sidePanel.getButtonList()){
          button.revalidate();
     }
      sidePanel.revalidate();
 }
}
