/*
 * Copyright (C) 2022 Jose
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package cu.edu.cujae.ed.snetwork.ui;

import cu.edu.cujae.ed.snetwork.logic.Person;
import java.awt.GridLayout;
import javax.swing.JPanel;

/**
 *
 * @author Jose
 */
public class SidePanel extends JPanel
{

    /**
     * Creates new form SidePanel
     */
    public SidePanel()
    {
        initComponents();
    }
    
    public void addPerson(Person p)
    {
        SideBarButton sdb = new SideBarButton(p);
        GridLayout gl = (GridLayout) sideBarContainer.getLayout();
        gl.setRows(gl.getRows() + 1);
        
        sideBarContainer.add(sdb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        sideBarContainer = new javax.swing.JPanel();

        setName("Usuarios"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        sideBarContainer.setName("Usuarios"); // NOI18N
        sideBarContainer.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane1.setViewportView(sideBarContainer);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel sideBarContainer;
    // End of variables declaration//GEN-END:variables
}
